baseURL = "http://localhost:1313/"
defaultContentLanguage = "en"
theme = "congo"
title = "partihaus"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menus.main]]
  name = "partihaus"
  url = "https://partihaus.com"
  weight = 5

[[menus.main]]
  name = "products"
  url = "/products/"
  weight = 10

[[menus.main]]
  name = "about"
  url = "/about/"
  weight = 20
