baseURL = "http://localhost:1313/"
defaultContentLanguage = "en"
theme = "congo"
title = "Partihaus"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
